spring:
  ai:
    mcp:
      server:
        enabled: true
        #所有客户端给这个端口发送请求，才知道有哪些工具，服务器通过这个端点返回工具集合
        sse-endpoint: /api/sse
        #客户端通过这个端点和服务器聊天
        sse-message-endpoint: /api/mcp/message
        capabilities:
          tool: true
logging:
  level:
    io.modelcontextprotocol: trace
    org.springframework: trace
server:
  port: 12000
