# Tomcat
server:
  port: 10002

# Spring
spring:
  application:
    # 应用名称
    name: user-service
  profiles:
    # 环境配置
    active: @profiles.active@
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
      enabled: on
--- # nacos 配置
spring:
  cloud:
    nacos:
      # nacos 服务地址
      server-addr: @nacos.server@
      username: @nacos.username@
      password: ${SPRING_CLOUD_NACOS_PASSWORD}
      discovery:
        # 注册组
        group: @nacos.discovery.group@
        namespace: ${spring.profiles.active}
      config:
        # 配置组
        group: @nacos.config.group@
        namespace: ${spring.profiles.active}
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:datasource.yml
      - optional:nacos:${spring.application.name}.yml


---
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token 前缀
  token-prefix: Bearer
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: tik
  # 是否输出操作日志
  is-log: true
  jwt-secret-key: ijfedkljhjkfhjksdhfkhsjh


spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: ${SPRING_DATA_REDIS_PASSWORD}
      database: 1


sms:
  baseUrl: https://dfsns.market.alicloudapi.com/data/send_sms
  method: Post
  appcode: 93b7e19861a24c519a7548b17dc16d75


app:
  executor:
    corePoolSize: 10
    maxPoolSize: 20
    keepAliveSeconds: 60
    queueCapacity: 500

